version: '2'

services:

  node:
    build: .
    command: node server.js
    container_name: 'node-app'
    env_file: docker.env
    ports:
      - 8080:8080    
    networks:
      - nodeapp-network
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
